spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=cource
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect

